### ISSUE TITLE
game crashing

### ISSUE THREAD

**Issue by nobodyoriginal** [Budschie/BudschieMorphMod#1]
I used /morphplayer myself and it keeps crashing my game now. I see the crash is from Size event at setNewSize(I was on server)

**Comment by Budschie** [comment]
Hello there.
Thanks for the reporting of this bug. Because you've closed this issue,
I am wondering whether if it resolved itself, or if you have closed this issue by accident.
So, I'd really appreciate it if you could provide me this information.
Best regards, Budschie.
