### ISSUE TITLE
[compat] RATS MOD -  net.minecraft.crash.ReportedException: Rendering entity in world

### ISSUE THREAD

**Issue by 0xicl33n** [Budschie/BudschieMorphMod#10]
I realize that this mod is still very much a work in progress and i very much appreciate all the hard work being done to bring morph to forge. 

I want to help test as many mobs/morphs as possible to help with compatibility. I am working on adding morph abilities to the rats.. the `rats:rat` entity seems to work just fine although i have not tested variations.. this crash happened when trying to morph into a `rats:plague_beast` 

`crash-2021-08-03_10.49.29-client.txt`
https://mclo.gs/tMy3tDD

You should make a discord server or something! this is outstanding work ❤️ 

`forge-36.2.0`
`bmorph-1.16.5-1.3.1.jar`
`rats-7.2.0-1.16.5.jar`
`citadel-1.7.2-1.16.5.jar`

**Comment by Budschie** [comment]
Alright, gonna have a look at this. Thanks for helping me developing and improving this mod.

**Comment by 0xicl33n** [comment]
Would like to add that this doesnt happen with just rats..but ocassionally other mobs..and if it does happen ,the player can no longer join the server until i wipe their playerdata....where are morphs stored?  what part of `word/playerdata/<uuid>.dat` has the list of morphs a player has?

**Comment by Budschie** [comment]
I think it is in ForgeCaps/bmorph:morph_cap. You should be able to just spawn in a demorphed state by yeeting the integer "currentMorphIndex" and "currentMorphItem" (if present) out. (I hope this helped). This reminds me that I should probably fix this issue that you spawn in as a random mob when exiting and entering a world again...

**Comment by 0xicl33n** [comment]
I've also started working on some modded mob abilities with my friends [here](https://github.com/0xicl33n/BudschieMorphMod/tree/master/src/main/resources/data/bmorph/morph_abilities)

**Comment by Budschie** [comment]
This issue should be fixed now with the latest release on CurseForge.
