### ISSUE TITLE
Crash on world load

### ISSUE THREAD

**Issue by KokuDuck** [Budschie/BudschieMorphMod#111]
I am using bmorph in addition to a few more. Minecraft works fine with all other mods but as soon as I add bmorph it crashes on world load. (Tried using only bmorph and new worlds. Didnt work)
[crash-2022-10-13_15.06.35-client.txt](https://github.com/Budschie/BudschieMorphMod/files/9776023/crash-2022-10-13_15.06.35-client.txt)

**Comment by Budschie** [comment]
This is probably a similar problem that the author of issue #86 had. I do think that this can be resolved pretty easily by simply updating the version of the mod from `1.18.2.1.0.0` (the version you are currently using) to `1.18.2.1.0.1` (the newest version currently available on CurseForge).

**Comment by KokuDuck** [comment]
It woked, thanks! :D
