### ISSUE TITLE
Outdated clients can join 1.4.1 servers - causes server crash

### ISSUE THREAD

**Issue by 0xicl33n** [Budschie/BudschieMorphMod#12]
I had a friend who didnt update their bmorph.. causes the server to crash when they crash.. should definitely add the "rejected because of mismatched mod version"

https://mclo.gs/f3S2mhj

fixed by restoring playerdata from before the hard crash from a few days ago, and telling said friend to update

**Comment by Budschie** [comment]
That outdated client part should not be a problem, as the only change that happened in 1.4.1 was a small change on the client to prevent a NoSuchElementException on the client when dying (fixing this issue was basically just adding a check to an if statement to test whether a value is present or not). The crash of the server on the other hand is a bit concerning though...

**Comment by Budschie** [comment]
From shortly looking at the logs, it seems that the crash is caused by an entity colliding with a furniture block by mrcrayfish that was chiseled with the chisel and bits mod lulw

**Comment by Budschie** [comment]
> That outdated client part should not be a problem, as the only change that happened in 1.4.1 was a small change on the client to prevent a NoSuchElementException on the client when dying (fixing this issue was basically just adding a check to an if statement to test whether a value is present or not). The crash of the server on the other hand is a bit concerning though...

This of course only applies if the outdated client is on version 1.4.0

**Comment by 0xicl33n** [comment]
My friend was on 1.3.1 and i had to restore playerdata from 2 days ago, before they caused the crash with the server version. They would instantly crash themselves, and the server..with a morph count of 87000

**Comment by Budschie** [comment]
Interesting... I'm still gonna have a look at this, as a server should never be crashed by a client.
