### ISSUE TITLE
[Crash]: Epic Fight incompatibility ( java.lang.ArithmeticException: / by zero)

### ISSUE THREAD

**Issue by Sx-e** [Budschie/BudschieMorphMod#129]
# The mod
* https://www.curseforge.com/minecraft/mc-mods/epic-fight-mod

# Minecraft Version
* 1.18.2

# What happened?
* Game crashes during loading a world.
### EpicFight-18.5.17.jar

# Crash log:

https://pastebin.com/ULm42Xrj

# Description:

### After loading a saved or new world, the game crashes which a couple of seconds.

**Comment by Sx-e** [comment]
Please, can you contact EpicFight mod dev to fix this issue?
Link to issue:
Yesssssman/epicfightmod/issues/1456

**Comment by Budschie** [comment]
Fixed in newest release :)

**Comment by Budschie** [comment]
Here's a link to the newest version btw: https://modrinth.com/mod/budschies-morph-mod/version/1.18.2-2.0.2
