### ISSUE TITLE
Use "Held Item" property with foxes

### ISSUE THREAD

**Issue by ZornTaov** [Budschie/BudschieMorphMod#2]
Would it be possible to add the ability to hold items with entities that are able to?  With Bipeds (Zombies, Skeletons, etc) it's already working, but foxes are able to hold items in their mouths. I think Villagers also hold items, and there might be others from other mods that use that property.

**Comment by Budschie** [comment]
Alright, I'm gonna work on it.

**Comment by Budschie** [comment]
Ok this bug should be fixed now. If you wonder why this bug existed in the first place, it existed because I tested item holding on skeletons, which have hands inverted. This inversion is now only applied to skeletons, and not to normal mobs, which means, that this bug should be fixed now.
