### ISSUE TITLE
Using command in command block causes mod to unload all commands

### ISSUE THREAD

**Issue by Kaleidio** [Budschie/BudschieMorphMod#22]
When my command block displays a command, all commands disappear from the game and the player becomes unable to execute the commands afterward.  What just happened here?

**Comment by Kaleidio** [comment]
On second thought it might be they just won't get registered on /reload for some reason.

**Comment by Kaleidio** [comment]
Nope, it is indeed after you view the command inside a command block

the command block will say the command is not found, then it also breaks in the chat.

**Comment by Budschie** [comment]
Alright, I've tried to reproduce this bug, however I did not manage to succeed at doing that. Please elaborate more on how to trigger such behaviour. For your interest, I could use the /morph command (or really any morph mod commands) whilst having an always active and repeating command block in the background executing "/demorph @a".

Maybe I should also note that I only tried to reproduce this bug in my current dev environment, which contains the newest code for this mod and also the optimal forge version. 

So, if this issue persists, please let me know.

**Comment by Kaleidio** [comment]
your commands remain if you never open that command block's console again.
