### ISSUE TITLE
More morph abilities?

### ISSUE THREAD

**Issue by userGabby** [Budschie/BudschieMorphMod#24]
I wanted more abilities like when I morph into a wither, I should be able to shoot wither skulls. If there is a way to make it in a data pack to add custom abilities, could you tell me?

**Comment by Budschie** [comment]
Well, there is currently no such thing as creating new abilities with data packs (maybe I'll add that in the future though). Sorry.

**Comment by userGabby** [comment]
Oh ok, thanks, pls do add that.
