### ISSUE TITLE
Entities will still "stare at" player even if morphed

### ISSUE THREAD

**Issue by Kaleidio** [Budschie/BudschieMorphMod#26]
Entities do not look at other entities, only at players.  This gives players away in a crowd.  Might it be possible to use a mixin to stop the lookat method from happening to players who are morphed?

**Comment by Budschie** [comment]
Ok, I've now added a gamerule that does the thing you proposed. Its name is "preventLookat", and it prevents entities from starting to look at you when you are morphed. However, the gamerule is set to false by default, so, when playing the next release of this mod, please set it to true if you want to do some hide and seek stuff.

With that said, thank you for contributing ideas to this project.
