### ISSUE TITLE
Death when morphing with low health

### ISSUE THREAD

**Issue by roguesensei** [Budschie/BudschieMorphMod#27]
### Bug
When morphing with low health, or morphing from a mob with low health (Such as a small magma cube) morphing into another creature causes player to die. Furthermore, the player does not drop their stuff on death and subsequent rejoins also cause the player to die when rejoining the game. 

I haven't been able to reproduce the issue in a fresh Singleplayer game, but I suspect the issue is down to a conflict with another mod (See modlist below) that alters player health.
### Workarounds
Two work-arounds we've discovered include:
- Deleting player data
- Modifying player NBT data to increase their health
### Environment
Mod version: 1.16.5-2.0.1
Forge version: 1.16-36.2.4
Game mode: Multiplayer
### Mod list
![Screenshot_2021-09-25_14-50-03](https://user-images.githubusercontent.com/32780495/134773750-e968ea68-47ba-449f-8a6e-75aeb0bd8801.png)

**Comment by Budschie** [comment]
This issue has been fixed for the 1.17.1 branch of this mod:
https://github.com/Budschie/BudschieMorphMod/commit/33074395e3bf16281e7a689c1649322a55695b9f
However, this fix is pretty new, so there is no new release containing this fix as of yet.

Edit: A new version containing the bug fix should be out now (or rather, it has been out for a while IIRC).
