### ISSUE TITLE
Crash when morphed and using Shrink. at the same time in F5

### ISSUE THREAD

**Issue by ZornTaov** [Budschie/BudschieMorphMod#3]
Crash Report: https://pastebin.com/0Hs9bzKA
Steps to reproduce:
Morph into something (I used the Minecraft Fox).
Use the shrinking device from Shrink. to try and become smaller fox.
Go into F5, immediately crash. (also crashes anyone around you in multiplayer)

Linked cross mod issue: https://github.com/gigabit101/Shrink/issues/31

**Comment by Budschie** [comment]
Alright, this issue should be fixed now :) I'm gonna upload this all to curse forge soon.
