### ISSUE TITLE
Losing all your stuff when dying.

### ISSUE THREAD

**Issue by Budschie** [Budschie/BudschieMorphMod#35]
Alright, it seems that there is a bug where you would lose your _whole_ inventory when dying,
I personally didn't experience it (yet), but many others have, so I'm gonna file this as a bug report now.

So, if you have encountered the same issue that is described above, please reply to this issue and tell me
how to trigger this bug so that I can fix it. 
Thanks.
-Budschie

**Comment by AFinalWord** [comment]
I can't seem to find any reason as to why this happens, like, no matter what options, or anything, I seem to lose my morph inventory too, if I turn off my op, if I make a new world with different settings, nothing works! The only thing I can think of is maybe the specific forge version causes it, have you encountered it yet? I'm using the forge version: 37.0.110, and I'm using the 1.17.1-1.0.0-beta, if you have a different forge version that doesn't lose the morph inventory then maybe it's a problem with the forge version? either way this is a really weird bug / glitch...

**Comment by Budschie** [comment]
The loss of the morph inventory is indeed a bug in my code, however, I have fixed it recently. This means that the bug fix will be included in the next version of this mod.
