### ISSUE TITLE
Latest version of mod (1.17.1-1.0.0-beta) with Optifine glitch

### ISSUE THREAD

**Issue by AFinalWord** [Budschie/BudschieMorphMod#44]
Whenever I break a block, no block breaking particles appear, no matter what kind of settings I choose or whatever, it does not make any block breaking particles and its really weird and annoys me a lot ;-; please fix! Thank you <3

**Comment by Budschie** [comment]
Alright, I'm gonna look into that issue. But there's probably nothing that I can do, I don't even use the particle system of MC in my mod IIRC.

I should also add that OptiFine is known to cause bugs on mods that extend the rendering system of MC.

Also, please check your OptiFine settings to see if you accidentally disabled particle effects.
\- Budschie

**Comment by Budschie** [comment]
Alright, I can definitely confirm that this happens.

**Comment by Budschie** [comment]
Alright, this is not an issue of mine but an OptiFine issue, because if I remove my mod (without changing the loader, so that I still use Forge to start MC), there are still no block breaking particles.

**Comment by Budschie** [comment]
In the preview release of OF, the block break particles seem to work again. So, you could try that. Or, you can just use alternatives of OptiFine, there are some pretty great options out there (although Sodium+Iris is Fabric only).
