### ISSUE TITLE
I cant morph

### ISSUE THREAD

**Issue by MemerGod64** [Budschie/BudschieMorphMod#5]
I press the button to toggle the UI and it wont open and I did collect souls to morph into.

**Comment by carnivorchild** [comment]
same thing for me.
 and when i use the morph command i'm very small and i can't fly like a bat

**Comment by Budschie** [comment]
@MemerGod64 I'd recommend reassigning the "Toggle Morph UI" keybind, as minecraft often glitches when it shows you the key that you should press. So, it would be best to just reassign the key and use that as your keybind. Please reply if that didn't work or if it did.

**Comment by MemerGod64** [comment]
I didn't work I changed the keybind to when I press o It should open

**Comment by Budschie** [comment]
@MemerGod64 
Alright, I've found the bug. In code, my gui only renders when the vignette renders. Of course, said vignette is disabled when using fast rendering or having it disabled in optifine. Re-enabling it should do the trick. In the next release, this bug will be fixed.

**Comment by Budschie** [comment]
Please tell me if that solved the issue.

**Comment by MemerGod64** [comment]
no I just collected a sheep soul and the Ui still won't open

**Comment by MemerGod64** [comment]
and I even restarted the game and got a chicken soul and still nothing

**Comment by Budschie** [comment]
Please attach a screenshot of minecraft (when the gui should be shown but isn't there).

**Comment by MemerGod64** [comment]
![image](https://user-images.githubusercontent.com/88213828/127746804-6b34b158-d7a8-416a-b965-a8c1ddae313c.png)

**Comment by MemerGod64** [comment]
![image](https://user-images.githubusercontent.com/88213828/127746985-08485377-d026-404a-b045-91eefc3a941c.png)

**Comment by Budschie** [comment]
Yeah, there is no vignette visible on this picture. Adding said vignette will fix the issue.

**Comment by Budschie** [comment]
I'm also currently working on a new release version of this mod where this issue is fixed, so even if it doesn't work now, it should in the future.

**Comment by MemerGod64** [comment]
what is vignette

**Comment by Budschie** [comment]
A vignette is an effect that makes everything in the corners dark.

**Comment by Budschie** [comment]
If you use optifine, you can find the vignette settings in Details and then there should be a vignette entry on the bottom left. If you are not using optifine, you can fix this problem by simply setting the graphics to fancy.

**Comment by MemerGod64** [comment]
ok

**Comment by MemerGod64** [comment]
thank you it worked

**Comment by carnivorchild** [comment]
the problem, tiny morph comes from the shrinking mode using the Personal Shrinking Device, I was able to find a normal size
