### ISSUE TITLE
Suggestion: A Morph animation

### ISSUE THREAD

**Issue by IntrovertedGamer** [Budschie/BudschieMorphMod#55]
I always thought this mod could use an animation for when you morph, it might not change much but it would add to the atmosphere to game and would really fit the Shapeshifter vibe, like how metamorph and the OG mod did.

**Comment by Budschie** [comment]
Alright, that's coming (at least to the 1.18 version), as I implemented this today.

**Comment by IntrovertedGamer** [comment]
Also, there's a bug where every time i die, i have to re-favorite all of the mobs i favorited in the past.

**Comment by IntrovertedGamer** [comment]
But thanks.

**Comment by Budschie** [comment]
> Also, there's a bug where every time i die, i have to re-favorite all of the mobs i favorited in the past.

Alright, I've gone ahead and fixed this issue. Thank you for reporting it :) (Commit Hash FYI: https://github.com/Budschie/BudschieMorphMod/commit/e885833910c1102bd93c1d979f54ac80931bdedd)
