### ISSUE TITLE
Mob Flight Edit

### ISSUE THREAD

**Issue by IntrovertedGamer** [Budschie/BudschieMorphMod#65]
I think the speed nerf of mobs that can fly was honestly too much, however i had a better suggestion in mind, instead of just slightly buffing the speed flying mobs again, i think you should instead make it so that different flying mobs have different speed, for example, a blaze moves at an average speed and is good for aerial attacks, however if you want to escape from something, a much better option to retreat would be a parrot or a bat as they are smaller and move faster, also for more combat and escape purposes, change it so that morphing into another flying mob while in the sky doesn't cause you to fall. Thanks.

**Comment by Budschie** [comment]
Your first issue (the balance thingy with the speed of the mobs) could be solved with data packs. Hopefully I will have enough time to eventually make a tutorial on how to create such a data pack.

**Comment by Budschie** [comment]
Alright, your issue will be fixed in the next release due to commit d4da83ce6ae4f25d42303d3e4a8e82a8c3e832a5. Thanks for supporting this bug. 

However, I myself discovered another bug where you would quit flying when leaving and re-entering the world. I'm (hopefully) gonna fix that bug in the future as well (though I would need to introduce a new system so that I can fix this bug).

**Comment by Budschie** [comment]
Ok, the issue that I described above is now fixed as well thanks to this commit: 16a7fc07b1fc2d4bd89e4becddcf27a094d87e27. Thanks for helping this project :)

**Comment by IntrovertedGamer** [comment]
thx

**Comment by IntrovertedGamer** [comment]
Yeah, i feel like flight speed in general should be more buffed again, you can't dodge things mid air anymore, it takes forever to fly from one place to another, and swimming has become a better alternative for travel, i'm not saying bring the old flight speed back but it should definitely be faster.
