### ISSUE TITLE
Cow, pig, and chicken preview flicker with quark

### ISSUE THREAD

**Issue by NotSoEpic** [Budschie/BudschieMorphMod#7]
https://user-images.githubusercontent.com/32610465/127729690-3bebaeb6-e002-4e6f-9cd2-abbb110ac2ef.mp4

The issue isn't present when morphed, a random texture is picked instead

**Comment by Budschie** [comment]
Yeah, I already encountered this one. I'm hopefully gonna fix this in the next release.

**Comment by Budschie** [comment]
So, I've now done the work so that this won't happen in the next release. The issue was that I was creating a entity that should be rendered every render (which is unperformant and memory-wise bad). This will be fixed in the new release (I've already pushed the fixed code to this repo).

**Comment by Budschie** [comment]
Alright, I can now empirically say that this issue is fixed.
