### ISSUE TITLE
Glow squid dont glow

### ISSUE THREAD

**Issue by albertosaurio65** [Budschie/BudschieMorphMod#80]
![2022-04-17_16 38 45](https://user-images.githubusercontent.com/70109413/163719462-83b56ca0-5bfa-4c68-9047-14000d69ee3c.png)

Unlike the original I don't shine

**Comment by Budschie** [comment]
Alright, I've fixed this issue with this commit: 90b30aeb74dd1278e01501f21f808ece3179d370. The change will be included in the next release.
