### ISSUE TITLE
1.18.2 server crash after player logged in

### ISSUE THREAD

**Issue by jelebruh** [Budschie/BudschieMorphMod#86]
When player joined to server it crashes with link to bmorph.refmap.json
[crash info txt](https://jelebruh.xyz/files/forgecrash.txt)

**Comment by Budschie** [comment]
Alright, I (probably) fixed it in this commit: a8a1a560fc70c65d1802db10a64c3c5201ce0749. This will hopefully be released soon as a new version.
Thanks for reporting this crash.
\- Budschie

**Comment by jelebruh** [comment]
> Alright, I (probably) fixed it in this commit: [a8a1a56](https://github.com/Budschie/BudschieMorphMod/commit/a8a1a560fc70c65d1802db10a64c3c5201ce0749).

We build it and all working good. Thanks.
