### ISSUE TITLE
Sitting position looks like your phasing through blocks, not sure if you could fix this but it seems like it's worth a shot.

### ISSUE THREAD

**Issue by IntrovertedGamer** [Budschie/BudschieMorphMod#88]
![2022-06-06_10 23 33](https://user-images.githubusercontent.com/89320207/172181543-36f40e53-5e08-4804-8746-ae0eac164b98.png)

**Comment by Budschie** [comment]
Alright, this will probably be a really easy fix, probably only a few lines of code and adding a tag.

**Comment by Budschie** [comment]
Fixed with this commit: 55dbdf3a5e0b2585fedf46e554a2bbaff7090692. It took longer than I expected tbh.
