### ISSUE TITLE
Crash when attacking a mimic from artifacts

### ISSUE THREAD

**Issue by Xplodin** [Budschie/BudschieMorphMod#94]
[crash-2022-06-10_01.04.50-client.txt](https://github.com/Budschie/BudschieMorphMod/files/8875902/crash-2022-06-10_01.04.50-client.txt)

Even when unmorphed it still does it

**Comment by Budschie** [comment]
Fixed with this commit 395d768c09138dae9faf3379b9681e2da2ae0800.

**Comment by Xplodin** [comment]
Mind if I build the current version and use it in my modpack?
It definitely seems to be fixed as of testing it in sp.
Also is there an eta on curseforge release?

**Comment by Budschie** [comment]
Nope, I would not mind if you were to built this mod from source and include it directly in your modpack - though I'd recommend you to pull and rebuild this mod again as I've noticed that I forgot to push some changes (namely, an ability for the evoker) to GitHub.
As for an ETA for a CurseForge release... I currently don't have one as I'm quite busy atm

**Comment by Kangy1103** [comment]
Hi,

Any updates on the CurseForge release for this please? Would really like to include it in my modpack but this issue is quite disruptive to gameplay.

Thank you

**Comment by Budschie** [comment]
Fix has been released on Curseforge.
